# Site settings
author: Damon Rocha
title: Software Engineering
header-img: img/home-bg.png
email: dmarcr1997@gmail.com
copyright_name: Damon Rocha
description: > # this means to ignore newlines until "baseurl:"
  Blog for Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dmarcr1997

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
